apiVersion: v1
kind: Pod
metadata:
  name: my-pod
  namespace: dev
  labels:
    app: xyz-app
spec:
  containers:
  - name: my-app
    image: nginx
    ports:
    - name: http
      containerPort: 80
      protocol: TCP